name: Listx
main: sx.cur.omnivion.listx.Listx
version: 1.0.2
author: Omnivion
database: false
website: http://cur.sx
commands:
  listx:
    description: List online staff
    aliases: [who, online, list]
    usage: /<command>